run:
  timeout: 5m
  allow-parallel-runners: true

issues:
  exclude-use-default: false
  exclude-rules:
    - path: "internal/*"
      linters:
        - dupl
    - path: "_test\\.go"
      linters:
        - errcheck

linters:
  disable-all: true
  enable:
    - dupl
    - errcheck
    - copyloopvar
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused

linters-settings:
  errcheck:
    exclude-functions:
      - fmt.Fprint
      - fmt.Fprintf
      - fmt.Fprintln
      - (net/http.ResponseWriter).Write
      - (*text/tabwriter.Writer).Flush
      - io.Copy(os.Stdout)
  revive:
    rules:
      - name: comment-spacings
