apiVersion: apps/v1
kind: Deployment
metadata:
  name: bob-controller-manager
  namespace: bob-system
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
        app: bob-api
    spec:
      serviceAccountName: bob-controller-manager
      containers:
        - name: manager
          image: controller:latest
          command:
            - /manager
          args:
            - --leader-elect
            - --api-bind-address=:8082
            - --cli-dir=/cli
            - --artifacts-dir=/data/artifacts
          ports:
            - name: api
              containerPort: 8082
              protocol: TCP
          volumeMounts:
            - name: artifacts
              mountPath: /data/artifacts
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 128Mi
      volumes:
        - name: artifacts
          emptyDir:
            sizeLimit: 1Gi
