apiVersion: builder.sdv.cloud.redhat.com/v1alpha1
kind: BuildJob
metadata:
  name: hello-world-shared-folder
  namespace: bob-builds
spec:
  toolchain:
    image: gcc:13
  source:
    type: pvc
    pvc:
      claimName: source-code
  target:
    platform: cmake
    architecture: native
  stages:
    - name: build
      command: "g++ /workspace/hello.cpp -o /workspace/bin/hello-world"
    - name: test
      command: "/workspace/bin/hello-world"
    - name: package
      command: "cp /workspace/bin/hello-world /workspace/artifacts/"
  artifacts:
    destination: pvc
    path: /workspace/artifacts
