apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bob-manager-role
rules:
  - apiGroups: ["builder.sdv.cloud.redhat.com"]
    resources:
      - buildjobs
      - buildjobs/status
      - buildjobs/finalizers
      - toolchains
      - toolchains/status
      - toolchains/finalizers
      - caches
      - caches/status
      - buildconfigs
      - buildconfigs/status
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "taskruns"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events", "secrets", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "patch", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch"]
  # Leader election
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
