//go:build !ignore_autogenerated

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

func (in *RuntimeSpec) DeepCopyInto(out *RuntimeSpec) { *out = *in }
func (in *RuntimeSpec) DeepCopy() *RuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(RuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *GitSource) DeepCopyInto(out *GitSource) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(SecretReference)
		**out = **in
	}
}
func (in *GitSource) DeepCopy() *GitSource {
	if in == nil {
		return nil
	}
	out := new(GitSource)
	in.DeepCopyInto(out)
	return out
}

func (in *PVCSource) DeepCopyInto(out *PVCSource) { *out = *in }
func (in *PVCSource) DeepCopy() *PVCSource {
	if in == nil {
		return nil
	}
	out := new(PVCSource)
	in.DeepCopyInto(out)
	return out
}

func (in *HostPathSource) DeepCopyInto(out *HostPathSource) { *out = *in }
func (in *HostPathSource) DeepCopy() *HostPathSource {
	if in == nil {
		return nil
	}
	out := new(HostPathSource)
	in.DeepCopyInto(out)
	return out
}

func (in *SourceSpec) DeepCopyInto(out *SourceSpec) {
	*out = *in
	if in.Git != nil {
		in, out := &in.Git, &out.Git
		*out = new(GitSource)
		(*in).DeepCopyInto(*out)
	}
	if in.PVC != nil {
		in, out := &in.PVC, &out.PVC
		*out = new(PVCSource)
		**out = **in
	}
	if in.HostPath != nil {
		in, out := &in.HostPath, &out.HostPath
		*out = new(HostPathSource)
		**out = **in
	}
}
func (in *SourceSpec) DeepCopy() *SourceSpec {
	if in == nil {
		return nil
	}
	out := new(SourceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *StageSpec) DeepCopyInto(out *StageSpec) { *out = *in }
func (in *StageSpec) DeepCopy() *StageSpec {
	if in == nil {
		return nil
	}
	out := new(StageSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PipelineStages) DeepCopyInto(out *PipelineStages) { *out = *in }
func (in *PipelineStages) DeepCopy() *PipelineStages {
	if in == nil {
		return nil
	}
	out := new(PipelineStages)
	in.DeepCopyInto(out)
	return out
}

func (in *DestinationSpec) DeepCopyInto(out *DestinationSpec) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(SecretReference)
		**out = **in
	}
}
func (in *DestinationSpec) DeepCopy() *DestinationSpec {
	if in == nil {
		return nil
	}
	out := new(DestinationSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *SoftwareBuildSpec) DeepCopyInto(out *SoftwareBuildSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	in.Destination.DeepCopyInto(&out.Destination)
}
func (in *SoftwareBuildSpec) DeepCopy() *SoftwareBuildSpec {
	if in == nil {
		return nil
	}
	out := new(SoftwareBuildSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *StageStatus) DeepCopyInto(out *StageStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
}
func (in *StageStatus) DeepCopy() *StageStatus {
	if in == nil {
		return nil
	}
	out := new(StageStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *SoftwareBuildStatus) DeepCopyInto(out *SoftwareBuildStatus) {
	*out = *in
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = make([]StageStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		copy(*out, *in)
	}
}
func (in *SoftwareBuildStatus) DeepCopy() *SoftwareBuildStatus {
	if in == nil {
		return nil
	}
	out := new(SoftwareBuildStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *SoftwareBuild) DeepCopyInto(out *SoftwareBuild) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}
func (in *SoftwareBuild) DeepCopy() *SoftwareBuild {
	if in == nil {
		return nil
	}
	out := new(SoftwareBuild)
	in.DeepCopyInto(out)
	return out
}
func (in *SoftwareBuild) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *SoftwareBuildList) DeepCopyInto(out *SoftwareBuildList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SoftwareBuild, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}
func (in *SoftwareBuildList) DeepCopy() *SoftwareBuildList {
	if in == nil {
		return nil
	}
	out := new(SoftwareBuildList)
	in.DeepCopyInto(out)
	return out
}
func (in *SoftwareBuildList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
