// Copyright 2026 Red Hat Inc.
// Licensed under the Apache License, Version 2.0.

//go:build !ignore_autogenerated

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *SecretReference) DeepCopyInto(out *SecretReference) { *out = *in }
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

func (in *ToolchainSpec) DeepCopyInto(out *ToolchainSpec) { *out = *in }
func (in *ToolchainSpec) DeepCopy() *ToolchainSpec {
	if in == nil {
		return nil
	}
	out := new(ToolchainSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *GitSource) DeepCopyInto(out *GitSource) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(SecretReference)
		**out = **in
	}
}
func (in *GitSource) DeepCopy() *GitSource {
	if in == nil {
		return nil
	}
	out := new(GitSource)
	in.DeepCopyInto(out)
	return out
}

func (in *PVCSource) DeepCopyInto(out *PVCSource) { *out = *in }
func (in *PVCSource) DeepCopy() *PVCSource {
	if in == nil {
		return nil
	}
	out := new(PVCSource)
	in.DeepCopyInto(out)
	return out
}

func (in *SourceSpec) DeepCopyInto(out *SourceSpec) {
	*out = *in
	if in.Git != nil {
		in, out := &in.Git, &out.Git
		*out = new(GitSource)
		(*in).DeepCopyInto(*out)
	}
	if in.PVC != nil {
		in, out := &in.PVC, &out.PVC
		*out = new(PVCSource)
		**out = **in
	}
}
func (in *SourceSpec) DeepCopy() *SourceSpec {
	if in == nil {
		return nil
	}
	out := new(SourceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetSpec) DeepCopyInto(out *TargetSpec) { *out = *in }
func (in *TargetSpec) DeepCopy() *TargetSpec {
	if in == nil {
		return nil
	}
	out := new(TargetSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *StageSpec) DeepCopyInto(out *StageSpec) { *out = *in }
func (in *StageSpec) DeepCopy() *StageSpec {
	if in == nil {
		return nil
	}
	out := new(StageSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *NamedStage) DeepCopyInto(out *NamedStage) { *out = *in }
func (in *NamedStage) DeepCopy() *NamedStage {
	if in == nil {
		return nil
	}
	out := new(NamedStage)
	in.DeepCopyInto(out)
	return out
}

func (in *OCIArtifactConfig) DeepCopyInto(out *OCIArtifactConfig) {
	*out = *in
	if in.PushSecret != nil {
		in, out := &in.PushSecret, &out.PushSecret
		*out = new(SecretReference)
		**out = **in
	}
	if in.Signing != nil {
		in, out := &in.Signing, &out.Signing
		*out = new(SigningConfig)
		(*in).DeepCopyInto(*out)
	}
}
func (in *OCIArtifactConfig) DeepCopy() *OCIArtifactConfig {
	if in == nil {
		return nil
	}
	out := new(OCIArtifactConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *SigningConfig) DeepCopyInto(out *SigningConfig) {
	*out = *in
	if in.CosignPasswordSecret != nil {
		in, out := &in.CosignPasswordSecret, &out.CosignPasswordSecret
		*out = new(SecretReference)
		**out = **in
	}
}
func (in *SigningConfig) DeepCopy() *SigningConfig {
	if in == nil {
		return nil
	}
	out := new(SigningConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *ArtifactSpec) DeepCopyInto(out *ArtifactSpec) {
	*out = *in
	if in.OCI != nil {
		in, out := &in.OCI, &out.OCI
		*out = new(OCIArtifactConfig)
		(*in).DeepCopyInto(*out)
	}
}
func (in *ArtifactSpec) DeepCopy() *ArtifactSpec {
	if in == nil {
		return nil
	}
	out := new(ArtifactSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *CacheMount) DeepCopyInto(out *CacheMount) { *out = *in }
func (in *CacheMount) DeepCopy() *CacheMount {
	if in == nil {
		return nil
	}
	out := new(CacheMount)
	in.DeepCopyInto(out)
	return out
}

func (in *BuildJobSpec) DeepCopyInto(out *BuildJobSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	out.Target = in.Target
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = make([]NamedStage, len(*in))
		copy(*out, *in)
	}
	in.Artifacts.DeepCopyInto(&out.Artifacts)
	if in.Caches != nil {
		in, out := &in.Caches, &out.Caches
		*out = make([]CacheMount, len(*in))
		copy(*out, *in)
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
}
func (in *BuildJobSpec) DeepCopy() *BuildJobSpec {
	if in == nil {
		return nil
	}
	out := new(BuildJobSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *StageStatus) DeepCopyInto(out *StageStatus) { *out = *in }
func (in *StageStatus) DeepCopy() *StageStatus {
	if in == nil {
		return nil
	}
	out := new(StageStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *BuildJobStatus) DeepCopyInto(out *BuildJobStatus) {
	*out = *in
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = make([]StageStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		copy(*out, *in)
	}
}
func (in *BuildJobStatus) DeepCopy() *BuildJobStatus {
	if in == nil {
		return nil
	}
	out := new(BuildJobStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *BuildJob) DeepCopyInto(out *BuildJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}
func (in *BuildJob) DeepCopy() *BuildJob {
	if in == nil {
		return nil
	}
	out := new(BuildJob)
	in.DeepCopyInto(out)
	return out
}
func (in *BuildJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *BuildJobList) DeepCopyInto(out *BuildJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BuildJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}
func (in *BuildJobList) DeepCopy() *BuildJobList {
	if in == nil {
		return nil
	}
	out := new(BuildJobList)
	in.DeepCopyInto(out)
	return out
}
func (in *BuildJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- Toolchain ---

func (in *ToolQualification) DeepCopyInto(out *ToolQualification) { *out = *in }
func (in *ToolQualification) DeepCopy() *ToolQualification {
	if in == nil {
		return nil
	}
	out := new(ToolQualification)
	in.DeepCopyInto(out)
	return out
}

func (in *ToolchainCRSpec) DeepCopyInto(out *ToolchainCRSpec) {
	*out = *in
	if in.SupportedBoards != nil {
		in, out := &in.SupportedBoards, &out.SupportedBoards
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SupportedArchitectures != nil {
		in, out := &in.SupportedArchitectures, &out.SupportedArchitectures
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Qualification != nil {
		in, out := &in.Qualification, &out.Qualification
		*out = new(ToolQualification)
		**out = **in
	}
}
func (in *ToolchainCRSpec) DeepCopy() *ToolchainCRSpec {
	if in == nil {
		return nil
	}
	out := new(ToolchainCRSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ToolchainCRStatus) DeepCopyInto(out *ToolchainCRStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		copy(*out, *in)
	}
}
func (in *ToolchainCRStatus) DeepCopy() *ToolchainCRStatus {
	if in == nil {
		return nil
	}
	out := new(ToolchainCRStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *Toolchain) DeepCopyInto(out *Toolchain) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}
func (in *Toolchain) DeepCopy() *Toolchain {
	if in == nil {
		return nil
	}
	out := new(Toolchain)
	in.DeepCopyInto(out)
	return out
}
func (in *Toolchain) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ToolchainList) DeepCopyInto(out *ToolchainList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Toolchain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}
func (in *ToolchainList) DeepCopy() *ToolchainList {
	if in == nil {
		return nil
	}
	out := new(ToolchainList)
	in.DeepCopyInto(out)
	return out
}
func (in *ToolchainList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- Cache ---

func (in *CacheCRSpec) DeepCopyInto(out *CacheCRSpec) { *out = *in }
func (in *CacheCRSpec) DeepCopy() *CacheCRSpec {
	if in == nil {
		return nil
	}
	out := new(CacheCRSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *CacheCRStatus) DeepCopyInto(out *CacheCRStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		copy(*out, *in)
	}
}
func (in *CacheCRStatus) DeepCopy() *CacheCRStatus {
	if in == nil {
		return nil
	}
	out := new(CacheCRStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *Cache) DeepCopyInto(out *Cache) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}
func (in *Cache) DeepCopy() *Cache {
	if in == nil {
		return nil
	}
	out := new(Cache)
	in.DeepCopyInto(out)
	return out
}
func (in *Cache) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *CacheList) DeepCopyInto(out *CacheList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cache, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}
func (in *CacheList) DeepCopy() *CacheList {
	if in == nil {
		return nil
	}
	out := new(CacheList)
	in.DeepCopyInto(out)
	return out
}
func (in *CacheList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- BuildConfig ---

func (in *BuildDefaultsSpec) DeepCopyInto(out *BuildDefaultsSpec) { *out = *in }
func (in *BuildDefaultsSpec) DeepCopy() *BuildDefaultsSpec {
	if in == nil {
		return nil
	}
	out := new(BuildDefaultsSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ComplianceSpec) DeepCopyInto(out *ComplianceSpec) { *out = *in }
func (in *ComplianceSpec) DeepCopy() *ComplianceSpec {
	if in == nil {
		return nil
	}
	out := new(ComplianceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *BuildAPISpec) DeepCopyInto(out *BuildAPISpec) { *out = *in }
func (in *BuildAPISpec) DeepCopy() *BuildAPISpec {
	if in == nil {
		return nil
	}
	out := new(BuildAPISpec)
	in.DeepCopyInto(out)
	return out
}

func (in *BuildConfigSpec) DeepCopyInto(out *BuildConfigSpec) { *out = *in }
func (in *BuildConfigSpec) DeepCopy() *BuildConfigSpec {
	if in == nil {
		return nil
	}
	out := new(BuildConfigSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *BuildConfigStatus) DeepCopyInto(out *BuildConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		copy(*out, *in)
	}
}
func (in *BuildConfigStatus) DeepCopy() *BuildConfigStatus {
	if in == nil {
		return nil
	}
	out := new(BuildConfigStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *BuildConfig) DeepCopyInto(out *BuildConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}
func (in *BuildConfig) DeepCopy() *BuildConfig {
	if in == nil {
		return nil
	}
	out := new(BuildConfig)
	in.DeepCopyInto(out)
	return out
}
func (in *BuildConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *BuildConfigList) DeepCopyInto(out *BuildConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BuildConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}
func (in *BuildConfigList) DeepCopy() *BuildConfigList {
	if in == nil {
		return nil
	}
	out := new(BuildConfigList)
	in.DeepCopyInto(out)
	return out
}
func (in *BuildConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
